[debug] [2025-06-02T11:40:00.218Z] ----------------------------------------------------------------------
[debug] [2025-06-02T11:40:00.221Z] Command:       /home/jules/.nvm/versions/node/v20.19.2/bin/node /home/swebot/.nvm/versions/node/v20.19.2/bin/firebase init --non-interactive --debug
[debug] [2025-06-02T11:40:00.221Z] CLI Version:   14.5.1
[debug] [2025-06-02T11:40:00.222Z] Platform:      linux
[debug] [2025-06-02T11:40:00.222Z] Node Version:  v20.19.2
[debug] [2025-06-02T11:40:00.222Z] Time:          Mon Jun 02 2025 11:40:00 GMT+0000 (Coordinated Universal Time)
[debug] [2025-06-02T11:40:00.222Z] ----------------------------------------------------------------------
[debug]
[debug] [2025-06-02T11:40:00.224Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2025-06-02T11:40:00.284Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-06-02T11:40:00.300Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:287:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoogleAuth._GoogleAuth_determineClient (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:834:32)
    at async GoogleAuth.getClient (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:698:20)
    at async GoogleAuth.getAccessToken (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:722:24)
    at async autoAuth (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/lib/requireAuth.js:26:19)
    at async Object.requireAuth [as fn] (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/lib/requireAuth.js:81:20)
    at async /home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/lib/command.js:242:17
[error]
[error] Error: Failed to authenticate, have you run firebase login?
[debug] [2025-06-02T11:40:00.325Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-06-02T11:40:00.325Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2025-06-02T11:40:11.283Z] ----------------------------------------------------------------------
[debug] [2025-06-02T11:40:11.286Z] Command:       /home/jules/.nvm/versions/node/v20.19.2/bin/node /home/swebot/.nvm/versions/node/v20.19.2/bin/firebase init emulators --non-interactive --debug
[debug] [2025-06-02T11:40:11.286Z] CLI Version:   14.5.1
[debug] [2025-06-02T11:40:11.287Z] Platform:      linux
[debug] [2025-06-02T11:40:11.287Z] Node Version:  v20.19.2
[debug] [2025-06-02T11:40:11.287Z] Time:          Mon Jun 02 2025 11:40:11 GMT+0000 (Coordinated Universal Time)
[debug] [2025-06-02T11:40:11.287Z] ----------------------------------------------------------------------
[debug]
[debug] [2025-06-02T11:40:11.293Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-06-02T11:40:11.322Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:287:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoogleAuth._GoogleAuth_determineClient (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:834:32)
    at async GoogleAuth.getClient (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:698:20)
    at async GoogleAuth.getAccessToken (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:722:24)
    at async autoAuth (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/lib/requireAuth.js:26:19)
    at async Object.requireAuth [as fn] (/home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/lib/requireAuth.js:81:20)
    at async /home/jules/.nvm/versions/node/v20.19.2/lib/node_modules/firebase-tools/lib/command.js:242:17
[error]
[error] Error: Failed to authenticate, have you run firebase login?
